dist: xenial

services:
  - redis

language: python

python:
  - "3.7"

install:
  - pip install codecov
  - pip install virtualenv
  - pip install -r requirements.txt 

before_install:
  - sudo apt-get update
#  - sudo apt-get install docker-ce
after_success:
#  - codecov

script:
  # - virtualenv venv
  # - source venv/bin/activate
  - python ./db/database.py
  # - python app.py
